---
branches:
  only:
  - source
language: ruby
rvm:
  - 1.9.3
before_script:
  - git config --global user.name "NickBoucart"
  - git config --global user.email "nboucart@gmail.com"
  - export REPO_URL="https://$GH_TOKEN@github.com/$GH_REPO.git"
  - bundle exec rake setup_github_pages[$REPO_URL]
script:
  - bundle exec rake generate
after_script:
  - bundle exec rake deploy
env:
  global:
  - GH_REPO="Nebucom/Nebucom.github.io"